name: Nightly Selenium Tests with Maven

on:
  schedule:
    - cron: '0 1 * * 1-5'

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and test with Maven
        run: mvn -B clean test -Dbrowser=Chrome -Durl=https://the-internet.herokuapp.com "-DexpectedTitle=The Internet"

      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports