name: Cloud Selenium Tests with Maven

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        required: true
        description: What browser should be used for the test?
        default: CloudChrome
        options:
          - CloudChrome

      url:
        required: true
        description: What url will be used?
        default: 'https://the-internet.herokuapp.com'
      expectedTitle:
        required: true
        description: Text the page title must contain
        default: 'The Internet'

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and test with Maven
        env:
          USERNAME: ${{ secrets.USERNAME }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        run: mvn -B clean test -Dbrowser=CloudChrome -Durl=${{github.event.inputs.url}} "-DexpectedTitle=${{github.event.inputs.expectedTitle}}"

      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports